// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event/event.proto

package event

import (
	context "context"
	fmt "fmt"
	request "github.com/dmirou/otusgo/calendar/pkg/contracts/request"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Desc                 string               `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	NotifyBefore         *duration.Duration   `protobuf:"bytes,7,opt,name=notify_before,json=notifyBefore,proto3" json:"notify_before,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_510ac585eaa75cc0, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Event) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Event) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Event) GetNotifyBefore() *duration.Duration {
	if m != nil {
		return m.NotifyBefore
	}
	return nil
}

type ListEventsPerDateRequest struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListEventsPerDateRequest) Reset()         { *m = ListEventsPerDateRequest{} }
func (m *ListEventsPerDateRequest) String() string { return proto.CompactTextString(m) }
func (*ListEventsPerDateRequest) ProtoMessage()    {}
func (*ListEventsPerDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_510ac585eaa75cc0, []int{1}
}

func (m *ListEventsPerDateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsPerDateRequest.Unmarshal(m, b)
}
func (m *ListEventsPerDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsPerDateRequest.Marshal(b, m, deterministic)
}
func (m *ListEventsPerDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsPerDateRequest.Merge(m, src)
}
func (m *ListEventsPerDateRequest) XXX_Size() int {
	return xxx_messageInfo_ListEventsPerDateRequest.Size(m)
}
func (m *ListEventsPerDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsPerDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsPerDateRequest proto.InternalMessageInfo

func (m *ListEventsPerDateRequest) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type ListEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventsResponse) Reset()         { *m = ListEventsResponse{} }
func (m *ListEventsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEventsResponse) ProtoMessage()    {}
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_510ac585eaa75cc0, []int{2}
}

func (m *ListEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventsResponse.Unmarshal(m, b)
}
func (m *ListEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventsResponse.Marshal(b, m, deterministic)
}
func (m *ListEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventsResponse.Merge(m, src)
}
func (m *ListEventsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEventsResponse.Size(m)
}
func (m *ListEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventsResponse proto.InternalMessageInfo

func (m *ListEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*ListEventsPerDateRequest)(nil), "event.ListEventsPerDateRequest")
	proto.RegisterType((*ListEventsResponse)(nil), "event.ListEventsResponse")
}

func init() {
	proto.RegisterFile("event/event.proto", fileDescriptor_510ac585eaa75cc0)
}

var fileDescriptor_510ac585eaa75cc0 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xa5, 0x1f, 0xe9, 0xe2, 0xa4, 0xab, 0xec, 0xe0, 0x47, 0x36, 0x8a, 0x96, 0xe2, 0x43, 0x17,
	0x25, 0x23, 0x55, 0x11, 0x7c, 0x50, 0xa9, 0x5d, 0x64, 0x45, 0x61, 0x89, 0x8a, 0xe0, 0xcb, 0x32,
	0xcd, 0xdc, 0x66, 0x87, 0x6d, 0x66, 0xe2, 0xcc, 0xcd, 0x42, 0x7f, 0x83, 0xff, 0xd8, 0x27, 0xc9,
	0x4c, 0x8a, 0xbb, 0xa9, 0xa8, 0xfb, 0xd2, 0xe6, 0x9e, 0x73, 0xee, 0x99, 0x9b, 0x73, 0x27, 0x64,
	0x0f, 0xce, 0x41, 0x21, 0x73, 0xbf, 0x49, 0x69, 0x34, 0x6a, 0x1a, 0xb8, 0x22, 0xbe, 0x97, 0x6b,
	0x9d, 0xaf, 0x80, 0xf1, 0x52, 0x32, 0xae, 0x94, 0x46, 0x8e, 0x52, 0x2b, 0xeb, 0x45, 0xf1, 0xdd,
	0x86, 0x75, 0xd5, 0xa2, 0x5a, 0x32, 0x28, 0x4a, 0x5c, 0x37, 0xe4, 0xfd, 0x36, 0x29, 0x2a, 0xe3,
	0xba, 0x1b, 0xfe, 0x41, 0x9b, 0x47, 0x59, 0x80, 0x45, 0x5e, 0x94, 0x8d, 0xe0, 0x96, 0x81, 0xef,
	0x15, 0x58, 0x64, 0xcd, 0xbf, 0x87, 0xc7, 0x3f, 0x3b, 0x24, 0x38, 0xac, 0x87, 0xa3, 0xd7, 0x49,
	0x57, 0x8a, 0xa8, 0x33, 0xea, 0x4c, 0xae, 0xa5, 0x5d, 0x29, 0xe8, 0x1d, 0xb2, 0x53, 0x59, 0x30,
	0x27, 0x52, 0x44, 0x5d, 0x07, 0x0e, 0xea, 0xf2, 0x48, 0xd0, 0x9b, 0x24, 0x40, 0x89, 0x2b, 0x88,
	0x7a, 0x0e, 0xf6, 0x05, 0xa5, 0xa4, 0x2f, 0xc0, 0x66, 0x51, 0xdf, 0x81, 0xee, 0x99, 0x3e, 0x21,
	0x81, 0x45, 0x6e, 0x30, 0x0a, 0x46, 0x9d, 0x49, 0x38, 0x8d, 0x13, 0x3f, 0x64, 0xb2, 0x19, 0x32,
	0xf9, 0xbc, 0x19, 0x32, 0xf5, 0x42, 0xfa, 0x98, 0xf4, 0x40, 0x89, 0x68, 0xf0, 0x4f, 0x7d, 0x2d,
	0xa3, 0xaf, 0xc8, 0xae, 0xd2, 0x28, 0x97, 0xeb, 0x93, 0x05, 0x2c, 0xb5, 0x81, 0x68, 0xc7, 0xf5,
	0xed, 0x6f, 0xf5, 0xcd, 0x9b, 0xb0, 0xd2, 0xa1, 0xd7, 0xcf, 0x9c, 0x7c, 0xfc, 0x9e, 0x44, 0x1f,
	0xa4, 0x45, 0xf7, 0xfe, 0xf6, 0x18, 0xcc, 0x9c, 0x23, 0xa4, 0x3e, 0x1e, 0x9a, 0x90, 0xbe, 0xe0,
	0x08, 0x2e, 0x90, 0xbf, 0x8f, 0xe2, 0x74, 0xe3, 0x97, 0x84, 0xfe, 0xf6, 0x4a, 0xc1, 0x96, 0x5a,
	0x59, 0xa0, 0x0f, 0xc9, 0xc0, 0xad, 0xde, 0x46, 0x9d, 0x51, 0x6f, 0x12, 0x4e, 0x87, 0x89, 0xbf,
	0x16, 0x4e, 0x96, 0x36, 0xdc, 0xf4, 0x47, 0x8f, 0x0c, 0x1d, 0xf2, 0x09, 0xcc, 0xb9, 0xcc, 0x80,
	0x1e, 0x90, 0xf0, 0xad, 0x01, 0x8e, 0xe0, 0x57, 0x73, 0xa9, 0x2b, 0xbe, 0x54, 0xd1, 0x47, 0x64,
	0xf8, 0x0e, 0xfc, 0xb1, 0xb3, 0xf5, 0xd1, 0x9c, 0xee, 0x26, 0x9b, 0x05, 0xd7, 0x65, 0x4b, 0x7c,
	0x40, 0xc2, 0x2f, 0xa5, 0xf8, 0x2f, 0xdf, 0x67, 0x24, 0x9c, 0xc3, 0x0a, 0x36, 0xd2, 0x96, 0xed,
	0xed, 0xad, 0x3c, 0x0e, 0xeb, 0xcb, 0x4a, 0x5f, 0x93, 0xbd, 0xad, 0x44, 0xe9, 0x8d, 0x0b, 0xbd,
	0x35, 0x10, 0xef, 0x37, 0x27, 0xfd, 0x21, 0xb0, 0xb6, 0xc1, 0x57, 0x80, 0xb3, 0x2b, 0x19, 0xbc,
	0xb9, 0xb8, 0x87, 0x63, 0x30, 0x1f, 0xb5, 0xc2, 0xd3, 0xab, 0x38, 0xcc, 0x5e, 0x7c, 0x7b, 0x9e,
	0x4b, 0x3c, 0xad, 0x16, 0x49, 0xa6, 0x0b, 0x26, 0x0a, 0x69, 0x74, 0xc5, 0x34, 0x56, 0x36, 0xd7,
	0x2c, 0xe3, 0x2b, 0x50, 0x82, 0x1b, 0x56, 0x9e, 0xe5, 0x2c, 0xd3, 0x0a, 0x0d, 0xcf, 0xd0, 0xfa,
	0x6f, 0x7d, 0x31, 0x70, 0x61, 0x3c, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x10, 0x8f, 0xf4, 0xa1,
	0x01, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	GetEventByID(ctx context.Context, in *request.ByID, opts ...grpc.CallOption) (*Event, error)
	UpdateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	DeleteEvent(ctx context.Context, in *request.ByID, opts ...grpc.CallOption) (*empty.Empty, error)
	ListEventsPerDate(ctx context.Context, in *request.ByDate, opts ...grpc.CallOption) (*ListEventsResponse, error)
	ListEventsPerWeek(ctx context.Context, in *request.ByDate, opts ...grpc.CallOption) (*ListEventsResponse, error)
	ListEventsPerMonth(ctx context.Context, in *request.ByDate, opts ...grpc.CallOption) (*ListEventsResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/event.EventService/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventByID(ctx context.Context, in *request.ByID, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/event.EventService/GetEventByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/event.EventService/UpdateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEvent(ctx context.Context, in *request.ByID, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/event.EventService/DeleteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListEventsPerDate(ctx context.Context, in *request.ByDate, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/ListEventsPerDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListEventsPerWeek(ctx context.Context, in *request.ByDate, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/ListEventsPerWeek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListEventsPerMonth(ctx context.Context, in *request.ByDate, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/ListEventsPerMonth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	CreateEvent(context.Context, *Event) (*Event, error)
	GetEventByID(context.Context, *request.ByID) (*Event, error)
	UpdateEvent(context.Context, *Event) (*Event, error)
	DeleteEvent(context.Context, *request.ByID) (*empty.Empty, error)
	ListEventsPerDate(context.Context, *request.ByDate) (*ListEventsResponse, error)
	ListEventsPerWeek(context.Context, *request.ByDate) (*ListEventsResponse, error)
	ListEventsPerMonth(context.Context, *request.ByDate) (*ListEventsResponse, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) CreateEvent(ctx context.Context, req *Event) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (*UnimplementedEventServiceServer) GetEventByID(ctx context.Context, req *request.ByID) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventByID not implemented")
}
func (*UnimplementedEventServiceServer) UpdateEvent(ctx context.Context, req *Event) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (*UnimplementedEventServiceServer) DeleteEvent(ctx context.Context, req *request.ByID) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (*UnimplementedEventServiceServer) ListEventsPerDate(ctx context.Context, req *request.ByDate) (*ListEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventsPerDate not implemented")
}
func (*UnimplementedEventServiceServer) ListEventsPerWeek(ctx context.Context, req *request.ByDate) (*ListEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventsPerWeek not implemented")
}
func (*UnimplementedEventServiceServer) ListEventsPerMonth(ctx context.Context, req *request.ByDate) (*ListEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventsPerMonth not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/GetEventByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventByID(ctx, req.(*request.ByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/UpdateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/DeleteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEvent(ctx, req.(*request.ByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListEventsPerDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ByDate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListEventsPerDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/ListEventsPerDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListEventsPerDate(ctx, req.(*request.ByDate))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListEventsPerWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ByDate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListEventsPerWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/ListEventsPerWeek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListEventsPerWeek(ctx, req.(*request.ByDate))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListEventsPerMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ByDate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListEventsPerMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/ListEventsPerMonth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListEventsPerMonth(ctx, req.(*request.ByDate))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "GetEventByID",
			Handler:    _EventService_GetEventByID_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventService_DeleteEvent_Handler,
		},
		{
			MethodName: "ListEventsPerDate",
			Handler:    _EventService_ListEventsPerDate_Handler,
		},
		{
			MethodName: "ListEventsPerWeek",
			Handler:    _EventService_ListEventsPerWeek_Handler,
		},
		{
			MethodName: "ListEventsPerMonth",
			Handler:    _EventService_ListEventsPerMonth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event/event.proto",
}
